// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAocux_0ypFrUGu8v35TbU12TOaQdCnhgs',
    appId: '1:140212970116:web:6d021186554eebafe318d1',
    messagingSenderId: '140212970116',
    projectId: 'raqamli-sovchi-988e7',
    authDomain: 'raqamli-sovchi-988e7.firebaseapp.com',
    storageBucket: 'raqamli-sovchi-988e7.firebasestorage.app',
    measurementId: 'G-FKNSR6GLPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4TzzUDWT6m68oYHUHRNO1KLQ5zB9OG2E',
    appId: '1:140212970116:android:70f75f05f1236d13e318d1',
    messagingSenderId: '140212970116',
    projectId: 'raqamli-sovchi-988e7',
    storageBucket: 'raqamli-sovchi-988e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbaIA_cofZk9YCqEE6R4IroA97a0YjJgc',
    appId: '1:140212970116:ios:752aa0320e76a0e6e318d1',
    messagingSenderId: '140212970116',
    projectId: 'raqamli-sovchi-988e7',
    storageBucket: 'raqamli-sovchi-988e7.firebasestorage.app',
    iosBundleId: 'app.raqamlisovchi.uz',
  );
}
